name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  terraform-provider-release:
    name: 'Terraform Provider Release'
    uses: hashicorp/ghaction-terraform-provider-release/.github/workflows/community.yml@v2
    secrets:
      gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
      gpg-private-key-passphrase: '${{ secrets.GPG_PASSPHRASE }}'
    with:
      setup-go-version: '1.18.x'
